### ISSUE TITLE
[DOC] - file should be removed from LICENSE.md link

### ISSUE THREAD

**Issue by bishal7679** [naomis-novas/community#127]
### What is incorrect in the documentation?

![Screenshot (149)](https://user-images.githubusercontent.com/70086051/175578493-8cf55cd3-f744-47a9-85bf-363261d37a3a.png)

### What should that text say?

![Screenshot (150)](https://user-images.githubusercontent.com/70086051/175581251-f73f1cbd-dd68-4522-8c9e-7d6fff7206cc.png)

**Comment by naomi-lgbt** [comment]
I don't believe this change needs to be made. Could you explain further?

**Comment by kelvinparmar** [comment]
Hey @naomi-lgbt  I would like to work on this issue. Please tell me what I have to do?

**Comment by bishal7679** [comment]
@kelvinparmar Thank you for showing interest. Actually I raised a PR against this issue but that got closed. I think this is not an issue for this particular docs now

**Comment by kelvinparmar** [comment]
So how can I contribute ? @bishal7679
