### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by vivekyadav19** [naomis-novas/community#262]
### Why do you want to join our organization?

There's a real sense of camaraderie and collaboration in this community that I really appreciate. Everyone is so willing to share their knowledge and support each other in their projects. It's a really positive and welcoming environment.

Although I am a newbie coder, still in my learning phase, I'm really passionate about open-source projects. Plus, I love the opportunity to meet and interact with new people and make lasting connections. This community seems like the perfect place to do all of those things.

**Comment by naomi-lgbt** [comment]
Invite sent~!
