### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by rajnishmanitiwari** [naomis-novas/community#263]
### Why do you want to join our organization?

I am interested in joining the community because I believe that it is a valuable resource for learning and collaboration. As a member of the community, I hope to contribute my own skills and insights while also learning from the experiences and knowledge of others. I am excited about the opportunity to be a part of such a talented and dedicated group of individuals.

**Comment by naomi-lgbt** [comment]
Invite sent~!
