### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by pratiksrivastava01** [naomis-novas/community#264]
### Why do you want to join our organization?

"Hello,

I am writing to express my interest in joining your organization as a beginner contributor. I am very enthusiastic about open-source contributions and believe that participating in a community like yours would be an excellent opportunity for me to learn and grow as a developer. I am eager to help the community in any way I can and believe I could make valuable contributions to your organization.

Thank you for considering my request. I look forward to the opportunity to work with your team and contribute to the growth of the open-source community.

Sincerely,
Pratik Srivastava"

**Comment by naomi-lgbt** [comment]
Invite sent~!
