### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by Krishnamohan-Yerrabilli** [naomis-novas/community#272]
### Why do you want to join our organization?

Joining your organization would give me the opportunity to collaborate with like-minded individuals on community projects, and contribute to the development and success of these projects. It would also provide a platform for me to share my skills and learn from others in the community. Overall, being a part of your organization would be a valuable and rewarding experience. Additionally, by joining your organization, I would have access to a variety of resources and tools that would allow me to expand my knowledge and improve my skills in a specific area of interest. I would also have the opportunity to network with other members of the community and potentially gain new perspectives and insights on various projects and topics. Furthermore, being a part of your organization would give me the chance to contribute to something meaningful and have a positive impact on the community. Overall, joining your organization would be a great way for me to grow both personally and professionally while also making a difference in the community.

**Comment by naomi-lgbt** [comment]
Invite sent~!
