### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by sidharthviz** [naomis-novas/community#281]
### Why do you want to join our organization?

I would love to join this organisation, and collaborate with peoples

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.nhcarrigan.com) too!

**Comment by sidharthviz** [comment]
> Invite sent~!
> 
> Be sure to join our [Discord](https://chat.nhcarrigan.com) too!

Sure
