### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by HMAHD** [naomis-novas/community#290]
### Why do you want to join our organization?

I want to join this community because I believe that it's important to have a supportive network of like-minded individuals who can offer guidance and inspiration as I continue to develop my skills and pursue my goals. I'm excited to contribute to the community in any way I can, and I look forward to learning from the other members.

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.nhcarrigan.com) too!
