### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by SazedWorldbringer** [naomis-novas/community#308]
### Why do you want to join our organization?

Hello! I'm Atharva Pardeshi, a self-taught software developer, focusing on full stack web development. I also spend my time studying core computer science topics and I love exploring tech in visual forms using Processing. When I'm not in front of the computer, I love to read books(from a wide range of genres), (try to) cook and spend time in the nature.

 I came across this community while looking for communities to be a part of on the internet to improve my skills and participate in meaningful discussions with people having similar interests. 

Excited to meet cool people and explore cool projects!

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!
