### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by SuperSmile0109** [naomis-novas/community#321]
### Why do you want to join our organization?

As a Senior Full Stack and Blockchain Engineer, I am very interested in this community.
I believe I can contribute some of my work to this community based on my Experience.
I am very thankful if you invite me to this community.

Thank you.

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!

**Comment by SuperSmile0109** [comment]
Thank you
