### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by MojoBoingo** [naomis-novas/community#352]
### Why do you want to join our organization?

Joined the Discord recently after first becoming more active in the FCC server. Just looking for relaxed communities where I can start contributing to open source stuff. Would love to join, even if I'll probably just observe for a while.

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!

**Comment by MojoBoingo** [comment]
Already there o/
