### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by geeky-sambhav** [naomis-novas/community#362]
### Why do you want to join our organization?

I have been following the naomis-novas community for some time now and have been impressed with the quality of work that has been produced by the members. I believe that my skills and experience would be a valuable asset to the community and I am eager to contribute to open-source projects and learn from other talented developers.

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!
