### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by PurpleMonkey729** [naomis-novas/community#380]
### Why do you want to join our organization?

Hi, excellent devs!
This is Yoshimura Hiroki, Japanese IT Engineer.
What I do best is React, ReactNative, Laravel and Django.
I am also interested in BlockChain and IoT.
Now I am researching about project management and algorithm logic.
I want to join to naomis-novas and I will contribute with my effort to grow up this organization.
Thanks for your reading.
Best regards!

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!
