### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by Sugamgoel28** [naomis-novas/community#382]
### Why do you want to join our organization?

I would love to join your GitHub community because of the vibrant and collaborative environment it offers. The opportunity to connect with like-minded individuals who share a passion for coding and development is highly appealing to me. By being a part of this community, I believe I can contribute to collective knowledge and learn from the expertise of others.

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!
