### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by truecolor0105** [naomis-novas/community#405]
### Why do you want to join our organization?

As a renowned and experienced software developer, I am constantly seeking opportunities to grow professionally and contribute my expertise to organizations that align with my values and goals. After conducting thorough research on your organization and the work you have done in the industry, I am impressed by the reputation and impact your organization has made.

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!
