### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by shibincreji** [naomis-novas/community#413]
### Why do you want to join our organization?

Joining an open-source community like Naomis's Novas as a beginner software engineer offers learning opportunities, skill development, networking, real-world problem-solving, teamwork experience, and a chance to give back to the community.

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!

**Comment by shibincreji** [comment]
Sure, Thank you
