### ISSUE TITLE
[ORG] Invite me to the organization

### ISSUE THREAD

**Issue by kumarankit999** [naomis-novas/community#415]
### Why do you want to join our organization?

I want to join your GitHub organization because to gain practical experience and learn from experienced developers. Being part of your organization can provide them with exposure to real-world projects, coding standards, and collaboration techniques. Joining your organization allows to connect with professionals and like-minded individuals in the industry. This networking opportunity can lead to mentorship, internships, or even job offers in the future.

**Comment by naomi-lgbt** [comment]
Invite sent~!

Be sure to join our [Discord](https://chat.naomi.lgbt) too!
